### PR TITLE
Fix: remove openssl-fips-provider

### PR DESCRIPTION
**Pull request by nazunalika**

### CODE REVIEW

**Comment by pajamian** [comment]
My main concern here is what will the effect of removing a dependancy of openssl-libs have on the remainder of the migration?  Will this break migrate2rocky9 if OL9 was installed in FIPS mode?

**Comment by nazunalika** [comment]
There's a high likelihood that it will. I put in a check for fips mode and it should stop everything until the user disables fips mode.

**Comment by pajamian** [comment]
That's good, but I would change line 276 to:
```
    if fips-mode-setup --is-enabled; then
```

**Comment by pajamian** [comment]
...oh, and add `fips-mode-setup` to the list of bins in bin_check as well.

**Review by pajamian — APPROVED** [review]

**Pull request merged**
