### PR TITLE
Add OpenELA lookaside to getsrc

### PR DESCRIPTION
**Pull request by maxbyte9p**
OpenELA's lookaside can be added to the getsrc grabber with minimal modification. I have also confirmed that the modified grabber works with OpenELA's lookaside.

### CODE REVIEW

**Comment by pajamian** [comment]
The lookaside is great but we should also have the remotes glob so that getsrc can find the correct lookaside without having to try all the other ones first.  What are the http and git remote URLs for OpenELA?

**Comment by maxbyte9p** [comment]
> The lookaside is great but we should also have the remotes glob so that getsrc can find the correct lookaside without having to try all the other ones first. What are the http and git remote URLs for OpenELA?

I will have to look into that. I also noticed that there is a branches section in the grabber for glob matching those. It's likely a good idea to add glob matches for the OpenELA branches as well. The OpenELA branches for example are named el-x.x

**Comment by maxbyte9p** [comment]
> > The lookaside is great but we should also have the remotes glob so that getsrc can find the correct lookaside without having to try all the other ones first. What are the http and git remote URLs for OpenELA?
> 
> I will have to look into that. I also noticed that there is a branches section in the grabber for glob matching those. It's likely a good idea to add glob matches for the OpenELA branches as well. The OpenELA branches for example are named el-x.x

`'@(git@|http?(s)://)github.com/openela-main/*'`

This is a working glob match for https cloned OpenELA repositories. As for ssh cloned I haven't gotten that figured out yet.

**Comment by pajamian** [comment]
> I also noticed that there is a branches section in the grabber for glob matching those. It's likely a good idea to add glob matches for the OpenELA branches as well. The OpenELA branches for example are named el-x.x

The branches only need to be matched if each branch has a different lookaside URL.  If the lookaside is the same for all the branches then there's no need to match the branch.

**Comment by maxbyte9p** [comment]
> > > The lookaside is great but we should also have the remotes glob so that getsrc can find the correct lookaside without having to try all the other ones first. What are the http and git remote URLs for OpenELA?
> > 
> > 
> > I will have to look into that. I also noticed that there is a branches section in the grabber for glob matching those. It's likely a good idea to add glob matches for the OpenELA branches as well. The OpenELA branches for example are named el-x.x
> 
> `'@(git@|http?(s)://)github.com/openela-main/*'`
> 
> This is a working glob match for https cloned OpenELA repositories. As for ssh cloned I haven't gotten that figured out yet.

`'@(git@|http?(s)://)github.com[:/]openela-main/*'`

I got a working glob match for both https and ssh cloned OpenELA repositories.

**Comment by maxbyte9p** [comment]
> Just add another blank entry to the branches array so it maintains parity with the other arrays.

Done.

**Review by pajamian — APPROVED** [review]
Looks good, thanks for the submission!

**Comment by maxbyte9p** [comment]
@pajamian @NeilHanlon No problem!

**Pull request merged**
