### PR TITLE
Install shellcheck from github releases

### PR DESCRIPTION
**Pull request by aminvakil**
Currently 0.7.2

### CODE REVIEW

**Comment by pajamian** [comment]
Pull from main to see how the checks look, and then I would like to see if this is still necessary after resolving the issue in mirror.sh.

**Comment by aminvakil** [comment]
> Pull from main to see how the checks look, and then I would like to see if this is still necessary after resolving the issue in mirror.sh.

It got fixed as expected.

**Comment by aminvakil** [comment]
Other than that, it's good to install shellcheck manually from github releases, otherwise we should for example stick to ubuntu-20.04 and cannot use ubuntu-latest github actions virtual environment, as it will probably use another shellcheck version and from previous experience they don't fully change ubuntu-latest in a snap.

GitHub increases percentage of ubuntu-22.04 little by little in a few months, so everyone can adapt to it, we do not need to tweak again for different shellcheck versions if we stick to our own installation.

**Comment by pajamian** [comment]
Okay, but why 2.7.2?  Why not go to 2.8.0 now?

**Comment by aminvakil** [comment]
> Okay, but why 0.7.2? Why not go to 0.8.0 now?

0.8.0 returned a warning, and archlinux has not bumped to 0.8.0 yet (I have asked why, but I didn't got a reply yet), so I was wondering if we fix the pipeline with sticking to 0.7.2 now, then try to figure it out if 0.8.0 has some problem or some other stuff, fix the warning it causes and bump it later.

**Comment by pajamian** [comment]
Okay, good enough for me.

**Pull request merged**
